# Generated by Django 5.1.1 on 2024-10-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_comparator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
